name: deploy on self-hosted runner
# run-name: ${{ github.workflow }} - ${{ github.ref }} - ${{ github.sha }}
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    env:
      SERVER_LOCAL_PATH: ~/servers/iser-public-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # - name: Use Node.js 18
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Remove previous build artifacts
        run: rm -rf ${{ env.SERVER_LOCAL_PATH }}/*

      - name: Move product
        run: cp -r ./dist/* ${{ env.SERVER_LOCAL_PATH }}/

      - name: Deploy project
        run: |
          pm2 startOrRestart ${{ env.SERVER_LOCAL_PATH }}/main.js --name IserPublicApi
        env:
          SERVER_PORT: 6990
          AUTHORITY_API_KEY: ${{ secrets.AUTHORITY_API_KEY }}
          WXWORK_WEBHOOK_URL: https://qyapi.weixin.qq.com/cgi-bin/webhook/send
      - name: remove node_modules
        run: rm -rf node_modules